# Generated by Django 4.0.1 on 2022-01-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
