# Generated by Django 4.0.1 on 2022-01-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user_id',
            new_name='user',
        ),
    ]
