# Generated by Django 4.0.1 on 2022-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0002_rename_user_id_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
